/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReposRouteImport } from './routes/repos'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as ReposIdRouteImport } from './routes/repos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposRoute = ReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIdRoute = ReposIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReposRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/repos': typeof ReposRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/repos/$id': typeof ReposIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/repos': typeof ReposRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/repos/$id': typeof ReposIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/repos': typeof ReposRouteWithChildren
  '/chat/$id': typeof ChatIdRoute
  '/repos/$id': typeof ReposIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/repos' | '/chat/$id' | '/repos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repos' | '/chat/$id' | '/repos/$id'
  id: '__root__' | '/' | '/repos' | '/chat/$id' | '/repos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReposRoute: typeof ReposRouteWithChildren
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos': {
      id: '/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$id': {
      id: '/repos/$id'
      path: '/$id'
      fullPath: '/repos/$id'
      preLoaderRoute: typeof ReposIdRouteImport
      parentRoute: typeof ReposRoute
    }
  }
}

interface ReposRouteChildren {
  ReposIdRoute: typeof ReposIdRoute
}

const ReposRouteChildren: ReposRouteChildren = {
  ReposIdRoute: ReposIdRoute,
}

const ReposRouteWithChildren = ReposRoute._addFileChildren(ReposRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReposRoute: ReposRouteWithChildren,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
